"""
List of Suzuki car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Suzuki-Swift GLX 1.2 DualJet",
    "Suzuki-Baleno Zeta 1.0 BoosterJet",
    "Suzuki-Dzire VDi AMT",
    "Suzuki-Vitara Brezza ZDi+",
    "Suzuki-Ciaz Alpha 1.5",
    "Suzuki-Jimny Sierra 1.5 AT",
    "Suzuki-Ertiga VXI 1.5 SHVS",
    "Suzuki-Ignis Zeta 1.2 AMT",
    "Suzuki-S-Cross Delta 1.4 BoosterJet",
    "Suzuki-Alto K10 VXi AGS"
]
