"""
List of Nio car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Nio-ES6 420km Signature Edition",
    "Nio-ES8 580km Performance Edition",
    "Nio-EC6 605km Sport Edition",
    "Nio-ET7 1000km Ultra-Long Range",
    "Nio-ET5 75kWh Standard Range",
    "Nio-ES7 100kWh Executive Edition",
    "Nio-EP9 Electric Supercar",
    "Nio-ET5 Touring 100kWh Long Range",
    "Nio-ES8 450km Business Edition",
    "Nio-EC7 700km Luxury Edition"
]
