"""
List of Nio car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "NIO EP9",
  "NIO ET7",
  "NIO ET5",
  "NIO ET9",
  "NIO ES8",
  "NIO ES6",
  "NIO EC6",
  "NIO EC7",
  "NIO EL8",
  "NIO EL7",
  "NIO EL6",
  "Onvo L60",
  "Onvo L80",
  "Onvo L90",
  "Firefly Compact EV"
]
