"""
List of Mazda car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Mazda3 Sedan",
  "Mazda3 Hatchback",
  "Mazda MX-5 Miata",
  "Mazda MX-5 Miata RF",
  "Mazda CX-30",
  "Mazda CX-30 2.5 S",
  "Mazda CX-30 2.5 S Select",
  "Mazda CX-30 2.5 S Preferred",
  "Mazda CX-30 2.5 S Premium",
  "Mazda CX-30 2.5 S Premium Plus",
  "Mazda CX-30 2.5 Turbo",
  "Mazda CX-30 2.5 Turbo Premium",
  "Mazda CX-30 2.5 Turbo Premium Plus",
  "Mazda CX-50",
  "Mazda CX-50 2.5 S Select",
  "Mazda CX-50 2.5 S Preferred",
  "Mazda CX-50 2.5 S Premium",
  "Mazda CX-50 2.5 S Premium Plus",
  "Mazda CX-50 2.5 Turbo Meridian Edition",
  "Mazda CX-50 2.5 Turbo Premium",
  "Mazda CX-50 2.5 Turbo Premium Plus",
  "Mazda CX-50 Hybrid",
  "Mazda CX-50 Hybrid Preferred",
  "Mazda CX-50 Hybrid Premium",
  "Mazda CX-50 Hybrid Premium Plus",
  "Mazda CX-5",
  "Mazda CX-5 S",
  "Mazda CX-5 S Select",
  "Mazda CX-5 S Preferred",
  "Mazda CX-5 S Premium",
  "Mazda CX-5 S Premium Plus",
  "Mazda CX-5 Turbo",
  "Mazda CX-5 Turbo Premium",
  "Mazda CX-5 Turbo Premium Plus",
  "Mazda CX-70"
]
