"""
List of Mazda car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Mazda-Mazda3 Sedan Compact 4-Door Sporty Car",
  "Mazda-Mazda3 Hatchback Versatile 5-Door Compact",
  "Mazda-MX-5 Miata Lightweight Convertible Roadster",
  "Mazda-MX-5 Miata RF Retractable Fastback Sports Car",
  "Mazda-CX-30 Subcompact Crossover SUV",
  "Mazda-CX-30 2.5 S Entry-Level Subcompact SUV",
  "Mazda-CX-30 2.5 S Select Stylish Urban Trim",
  "Mazda-CX-30 2.5 S Preferred Comfort-Focused Package",
  "Mazda-CX-30 2.5 S Premium High-End Interior Features",
  "Mazda-CX-30 2.5 S Premium Plus Fully Loaded Subcompact",
  "Mazda-CX-30 2.5 Turbo Performance-Oriented Turbocharged SUV",
  "Mazda-CX-30 2.5 Turbo Premium Turbo SUV with Upscale Features",
  "Mazda-CX-30 2.5 Turbo Premium Plus Top-Tier Turbo Model",
  "Mazda-CX-50 Rugged Compact Adventure SUV",
  "Mazda-CX-50 2.5 S Select Well-Equipped Entry Trim",
  "Mazda-CX-50 2.5 S Preferred Comfort and Convenience Package",
  "Mazda-CX-50 2.5 S Premium Feature-Rich Mid-Trim",
  "Mazda-CX-50 2.5 S Premium Plus Fully Loaded Naturally Aspirated Model",
  "Mazda-CX-50 2.5 Turbo Meridian Edition Outdoor Adventure Package",
  "Mazda-CX-50 2.5 Turbo Premium Turbocharged Power and Luxury",
  "Mazda-CX-50 2.5 Turbo Premium Plus High-End Turbo Trim",
  "Mazda-CX-50 Hybrid Efficient AWD Crossover",
  "Mazda-CX-50 Hybrid Preferred Enhanced Comfort and Tech",
  "Mazda-CX-50 Hybrid Premium Feature-Rich Hybrid SUV",
  "Mazda-CX-50 Hybrid Premium Plus Fully Equipped Hybrid Trim",
  "Mazda-CX-5 Best-Selling Compact Crossover",
  "Mazda-CX-5 S Standard Compact SUV",
  "Mazda-CX-5 S Select Balanced Value and Features",
  "Mazda-CX-5 S Preferred Comfort-Focused Edition",
  "Mazda-CX-5 S Premium Upscale Interior Package",
  "Mazda-CX-5 S Premium Plus Fully Loaded Naturally Aspirated Model",
  "Mazda-CX-5 Turbo Performance-Driven Compact SUV",
  "Mazda-CX-5 Turbo Premium Turbocharged Power and Luxury",
  "Mazda-CX-5 Turbo Premium Plus Top-Tier Turbo Trim",
  "Mazda-CX-70 Midsize SUV with Two-Row Seating"
]
