"""
List of Mazda car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Mazda-CX-5 Carbon Edition Turbo AWD",
    "Mazda-MX-5 Miata RF Club",
    "Mazda-3 Sedan 2.5 Turbo Premium Plus",
    "Mazda-CX-30 Select",
    "Mazda-6 Signature",
    "Mazda-MX-30 Premium Plus",
    "Mazda-CX-9 Grand Touring",
    "Mazda-BT-50 Thunder 4x4",
    "Mazda-2 Sedan 1.5 GL",
    "Mazda-RX-8 Type S"
]
