"""
List of Geely car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Geely-Emgrand",
  "Geely-Emgrand L",
  "Geely-Emgrand EV Pro",
  "Geely-Binrui",
  "Geely-Xingrui",
  "Geely-Preface",
  "Geely-Binyue",
  "Geely-Boyue",
  "Geely-Boyue Cool",
  "Geely-Boyue L",
  "Geely-Xingyue",
  "Geely-Xingyue L",
  "Geely-Haoyue",
  "Geely-Icon",
  "Geely-Starray",
  "Geely-Monjaro",
  "Geely-Coolray",
  "Geely-GX3 Pro",
  "Geely-Okavango",
  "Geely-Panda Mini EV",
  "Geely-Panda Knight",
  "Geely-Cowboy",
  "Geely-Jiaji",
  "Geely-Galaxy L6",
  "Geely-Galaxy L7",
  "Geely-Galaxy E5",
  "Geely-Galaxy E8",
  "Geely-Galaxy Starship 7",
  "Geely-Geometry A",
  "Geely-Geometry A Pro",
  "Geely-Geometry G6",
  "Geely-Geometry C",
  "Geely-Geometry M6",
  "Geely-Geometry E",
  "Geely-Geometry Panda"
]
