"""
List of Geely car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Geely-Boyue Pro 1.8TD DCT",
    "Geely-Emgrand GL 1.4T CVT",
    "Geely-Geometry A 600 Pro",
    "Geely-Haoqing 1.5L MT",
    "Geely-Prefacelift Emgrand X7 2.4L AT",
    "Geely-Binrui 1.0T MHEV",
    "Geely-Xingyue L 2.0TD 4WD",
    "Geely-Tugella 1.5T PHEV",
    "Geely-Panda Cross 1.3L MT",
    "Geely-Atlas Pro 1.5TD DCT"
]
