"""
List of XiaoMi car models
Generated by create_model_list.py script
These are real car models across different price ranges
"""

model_list = [
 "Xiaomi-SU7",
  "Xiaomi-SU7 Standard Range",
  "Xiaomi-SU7 Long Range",
  "Xiaomi-SU7 Pro",
  "Xiaomi-SU7 Max",
  "Xiaomi-SU7 Max AWD",
  "Xiaomi-SU7 Ultra AWD",
]
