"""
List of XiaoMi car models
Generated by create_model_list.py script
These are real car models across different price ranges
"""

model_list = [
    "XiaoMi-SU7",
    "XiaoMi-SU7 Ultra",
    "XiaoMi-Yu7",
]
