"""
List of Audi car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Audi-A4 45 TFSI quattro S line",
    "Audi-Q7 55 TFSI e quattro",
    "Audi-RS6 Avant Performance",
    "Audi-e-tron GT quattro",
    "Audi-A3 35 TFSI Sportback S tronic"
]
