"""
List of Peugeot car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Peugeot-208 Style Entry-Level Urban Hatchback",
  "Peugeot-208 Allure Mid-Trim Compact Hatchback",
  "Peugeot-208 GT Sporty Performance Hatchback",
  "Peugeot-208 GTi High-Performance Hot Hatch",
  "Peugeot-2008 Active Entry-Level Subcompact SUV",
  "Peugeot-2008 Allure Mid-Trim City SUV",
  "Peugeot-2008 GT Sporty Urban Crossover",
  "Peugeot-2008 GTi Performance Edition SUV",
  "Peugeot-308 Style Affordable Compact Hatchback",
  "Peugeot-308 Allure Refined Urban Hatchback",
  "Peugeot-308 GT Sporty Hatchback Edition",
  "Peugeot-308 GTi Performance Compact Hot Hatch",
  "Peugeot-308 SW Practical Estate/Wagon Version",
  "Peugeot-408 Active Entry-Level Fastback Crossover",
  "Peugeot-408 Allure Sleek Coupe-Like Crossover",
  "Peugeot-408 GT Sporty Fastback with GT Trim",
  "Peugeot-408 GTi High-Performance Crossover Coupe",
  "Peugeot-3008 Active Versatile Compact SUV",
  "Peugeot-3008 Allure Refined SUV with Modern Tech",
  "Peugeot-3008 GT Sporty and Premium Compact SUV",
  "Peugeot-3008 GTi High-Performance SUV Trim",
  "Peugeot-3008 E-3008 Fully Electric Compact SUV",
  "Peugeot-3008 E-3008 Long Range Extended Battery Range",
  "Peugeot-3008 E-3008 4x4 All-Wheel Drive Electric SUV",
  "Peugeot-5008 Active Entry Three-Row Family SUV",
  "Peugeot-5008 Allure Well-Equipped Midsize SUV",
  "Peugeot-5008 GT Premium 7-Seater SUV",
  "Peugeot-5008 GTi Performance-Oriented Midsize SUV",
  "Peugeot-5008 E-5008 All-Electric 3-Row SUV",
  "Peugeot-5008 E-5008 Long Range Extended EV Range Model",
  "Peugeot-5008 E-5008 4x4 Electric All-Wheel Drive SUV",
  "Peugeot-1008 Active Affordable Compact City Car",
  "Peugeot-1008 Allure Stylish Urban Hatchback",
  "Peugeot-1008 GT Performance-Inspired Mini Hatch",
  "Peugeot-E-208 GT Electric Version of Performance Hatch",
  "Peugeot-E-2008 Allure Electric Subcompact SUV",
  "Peugeot-E-2008 GT High-Trim Electric Urban SUV",
  "Peugeot-E-308 Allure Electric Hatchback with Style",
  "Peugeot-E-308 GT Premium Electric Hatchback Trim",
  "Peugeot-E-408 Allure Stylish Electric Crossover Coupe",
  "Peugeot-E-408 GT Sporty Electric Fastback Crossover",
  "Peugeot-E-Partner Standard Electric Commercial Van",
  "Peugeot-E-Partner Long Extended Cargo Electric Van"
]
