"""
List of Peugeot car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Peugeot 208 Style",
  "Peugeot 208 Allure",
  "Peugeot 208 GT",
  "Peugeot 208 GTi",
  "Peugeot 2008 Active",
  "Peugeot 2008 Allure",
  "Peugeot 2008 GT",
  "Peugeot 2008 GTi",
  "Peugeot 308 Style",
  "Peugeot 308 Allure",
  "Peugeot 308 GT",
  "Peugeot 308 GTi",
  "Peugeot 308 SW",
  "Peugeot 408 Active",
  "Peugeot 408 Allure",
  "Peugeot 408 GT",
  "Peugeot 408 GTi",
  "Peugeot 3008 Active",
  "Peugeot 3008 Allure",
  "Peugeot 3008 GT",
  "Peugeot 3008 GTi",
  "Peugeot 3008 E-3008",
  "Peugeot 3008 E-3008 Long Range",
  "Peugeot 3008 E-3008 4x4",
  "Peugeot 5008 Active",
  "Peugeot 5008 Allure",
  "Peugeot 5008 GT",
  "Peugeot 5008 GTi",
  "Peugeot 5008 E-5008",
  "Peugeot 5008 E-5008 Long Range",
  "Peugeot 5008 E-5008 4x4",
  "Peugeot 1008 Active",
  "Peugeot 1008 Allure",
  "Peugeot 1008 GT",
  "Peugeot E-208 GT",
  "Peugeot E-2008 Allure",
  "Peugeot E-2008 GT",
  "Peugeot E-308 Allure",
  "Peugeot E-308 GT",
  "Peugeot E-408 Allure",
  "Peugeot E-408 GT",
  "Peugeot E-Partner Standard",
  "Peugeot E-Partner Long"
]
