"""
List of Peugeot car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Peugeot-208 GT Line 1.2 PureTech 130",
    "Peugeot-308 GT 1.6 THP 270",
    "Peugeot-508 SW GT 2.0 BlueHDi 180",
    "Peugeot-2008 GT Pack 1.2 PureTech 155",
    "Peugeot-3008 GT Line 1.6 Hybrid 225",
    "Peugeot-5008 Allure 1.5 BlueHDi 130",
    "Peugeot-108 Active 1.0 VTi 72",
    "Peugeot-Rifter GT 1.5 BlueHDi 130",
    "Peugeot-Traveller Business 2.0 BlueHDi 150",
    "Peugeot-e-208 GT 50kWh"
]
