"""
List of Changan car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Changan-UNI-T 1.5T Premium",
    "Changan-UNI-K 2.0T AWD",
    "Changan-CS75 PLUS 2.0TGDI",
    "Changan-Eado DT 1.6L Luxury",
    "Changan-Raeton CC 1.5T Elite",
    "Changan-Benni EV360",
    "Changan-ALSVIN 1.4T Comfort",
    "Changan-CS35 PLUS 1.4T Blue Core",
    "Changan-Hunter 2.0T 4WD",
    "Changan-Deepal SL03 515EV"
]
