"""
List of Changan car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Changan-CS35 Plus",
  "Changan-CS55 Plus",
  "Changan-CS75 Plus",
  "Changan-CS75 Pro",
  "Changan-CS85",
  "Changan-CS95",
  "Changan-UNI-T",
  "Changan-UNI-K",
  "Changan-UNI-Z",
  "Changan-UNI-V",
  "Changan-Raeton Plus",
  "Changan-Eado",
  "Changan-Eado EV",
  "Changan-Lumin",
  "Changan-F70",
  "Changan-Hunter"
]
