"""
List of Volvo car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Volvo-XC40 Recharge Twin Ultimate",
    "Volvo-XC60 B5 AWD Inscription",
    "Volvo-XC90 T8 R-Design Plug-in Hybrid",
    "Volvo-S60 T8 Polestar Engineered",
    "Volvo-V60 Cross Country B6 AWD Ultimate",
    "Volvo-C40 Recharge Twin Plus",
    "Volvo-S90 T6 AWD Inscription",
    "Volvo-XC40 T5 Momentum",
    "Volvo-V90 CC B5 AWD Inscription",
    "Volvo-XC60 Recharge T8 eAWD R-Design"
]
