"""
List of Hyundai car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Hyundai-Elantra Limited 2.0L",
    "Hyundai-Sonata SEL Plus 1.6T",
    "Hyundai-Tucson Limited 1.6T AWD",
    "Hyundai-Santa Fe Calligraphy 2.5T",
    "Hyundai-Kona Electric Ultimate",
    "Hyundai-Palisade Calligraphy AWD",
    "Hyundai-Veloster N 2.0T",
    "Hyundai-Ioniq 5 Limited RWD",
    "Hyundai-Accent SE 1.6L",
    "Hyundai-Nexo Blue"
]
