"""
List of Volkswagen car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Volkswagen-Golf R 2.0T 4Motion",
    "Volkswagen-Jetta GLI 2.0T Autobahn",
    "Volkswagen-Tiguan SEL Premium R-Line 4Motion",
    "Volkswagen-Arteon 2.0T SEL Premium R-Line",
    "Volkswagen-Atlas Cross Sport V6 SEL Premium",
    "Volkswagen-ID.4 Pro S AWD",
    "Volkswagen-Passat GT 2.0T",
    "Volkswagen-Touareg V8 TDI Executive",
    "Volkswagen-e-Golf SEL Premium",
    "Volkswagen-T-Roc 1.5 TSI R-Line"
]
