"""
List of Nissan car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Nissan-Altima SR VC-Turbo",
    "Nissan-Rogue Platinum AWD",
    "Nissan-Maxima SR Midnight Edition",
    "Nissan-Sentra SV Premium Package",
    "Nissan-Pathfinder Rock Creek Edition",
    "Nissan-Frontier PRO-4X Crew Cab",
    "Nissan-Titan XD Platinum Reserve Diesel",
    "Nissan-Leaf SV Plus",
    "Nissan-Z Performance 6MT",
    "Nissan-Armada SL 4x4"
]
