"""
List of Nissan car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Nissan Versa",
  "Nissan Sentra",
  "Nissan Altima",
  "Nissan Maxima",
  "Nissan Z",
  "Nissan Kicks",
  "Nissan Rogue",
  "Nissan Rogue Rock Creek",
  "Nissan Murano",
  "Nissan Pathfinder",
  "Nissan Armada",
  "Nissan Ariya",
  "Nissan Leaf",
  "Nissan Frontier",
  "Nissan Titan",
  "Nissan Titan XD"
]
