"""
List of BYD car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "BYD-Han EV 605km Long Range",
    "BYD-Tang EV 4WD 517hp",
    "BYD-Qin Plus DM-i 120km",
    "BYD-Song Plus EV 510km Premium",
    "BYD-Yuan Plus 430km Standard Range",
    "BYD-Seal 550km RWD",
    "BYD-Dolphin 405km Dynamic",
    "BYD-F5 DM-i 55km Comfort",
    "BYD-e6 400km Premium",
    "BYD-Atto 3 150kW Extended Range"
]
