"""
List of Porsche car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Porsche-911 Turbo S Cabriolet",
    "Porsche-Taycan Turbo S Cross Turismo",
    "Porsche-Cayenne Turbo GT",
    "Porsche-Panamera 4S E-Hybrid",
    "Porsche-718 Cayman GT4 RS",
    "Porsche-Macan GTS",
    "Porsche-911 Carrera 4 GTS",
    "Porsche-Taycan 4S",
    "Porsche-Cayenne S Coupe",
    "Porsche-718 Boxster T"
]
