"""
List of Ford car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Ford-F-150 Lariat 3.5L EcoBoost",
    "Ford-Mustang GT Premium 5.0L V8",
    "Ford-Edge ST 2.7L EcoBoost",
    "Ford-Escape Titanium 1.5L EcoBoost",
    "Ford-Expedition Platinum 3.5L EcoBoost",
    "Ford-Ranger XLT 2.3L EcoBoost",
    "Ford-Bronco Badlands 2.7L EcoBoost",
    "Ford-Maverick Lariat Hybrid 2.5L",
    "Ford-Focus ST 2.3L EcoBoost",
    "Ford-Explorer Limited 3.0L EcoBoost"
]
