"""
List of Cadillac car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Cadillac-XT4",
  "Cadillac-XT5",
  "Cadillac-XT6",
  "Cadillac-XT6 Premium Luxury",
  "Cadillac-XT5 Sport",
  "Cadillac-XT4 Sport",
  "Cadillac-CT4",
  "Cadillac-CT4 V-Series",
  "Cadillac-CT5",
  "Cadillac-CT5 V-Series",
  "Cadillac-CT5-V Blackwing",
  "Cadillac-CTS",
  "Cadillac-CTS V",
  "Cadillac-CTS-V Blackwing",
  "Cadillac-Escalade",
  "Cadillac-Escalade ESV",
  "Cadillac-Escalade V-Series",
  "Cadillac-Lyriq",
  "Cadillac-Lyriq AWD",
  "Cadillac-CT6",
  "Cadillac-CT6 V-Sport",
  "Cadillac-ELR",
  "Cadillac-Grand Prix",
  "Cadillac-SRX",
  "Cadillac-XTS",
  "Cadillac-Vista",
  "Cadillac-Cadillac V-Series Blackwing",
  "Cadillac-Escalade IQ"
]
 