"""
List of Cadillac car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Cadillac-CT5-V Blackwing",
    "Cadillac-Escalade ESV Platinum 6.2L",
    "Cadillac-XT5 Premium Luxury 3.6L",
    "Cadillac-CT4-V AWD 2.7L",
    "Cadillac-XT6 Sport 3.6L",
    "Cadillac-ATS-V Coupe 3.6L Twin-Turbo",
    "Cadillac-DTS Luxury III 4.6L",
    "Cadillac-STS-V 4.4L Supercharged",
    "Cadillac-SRX Premium Collection 3.0L",
    "Cadillac-ELR Extended Range Electric"
]
