"""
List of Honda car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Honda-Accord EX-L 2.0T",
    "Honda-Civic Type R Limited Edition 2021",
    "Honda-CRV Touring Hybrid",
    "Honda-Pilot Elite AWD",
    "Honda-Odyssey EX-L Navi",
    "Honda-Fit EX 1.5L",
    "Honda-Ridgeline RTL-E",
    "Honda-Insight Touring",
    "Honda-Passport TrailSport",
    "Honda-HR-V EX-L"
]
