"""
List of Bentley car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Bentley-Continental GT",
  "Bentley-Continental GT V8",
  "Bentley-Continental GT Speed",
  "Bentley-Continental GT Mulliner",
  "Bentley-Continental GT Mulliner Convertible",
  "Bentley-Continental GTC",
  "Bentley-Continental GTC Speed Convertible",
  "Bentley-Bentayga",
  "Bentley-Bentayga V8",
  "Bentley-Bentayga Speed",
  "Bentley-Bentayga Hybrid",
  "Bentley-Bentayga Azure",
  "Bentley-Bentley-Bolide",
  "Bentley-Flying Spur",
  "Bentley-Flying Spur W12",
  "Bentley-Flying Spur V8",
  "Bentley-Flying Spur Speed",
  "Bentley-Flying Spur Hybrid",
  "Bentley-Flying Spur Mulliner",
  "Bentley-Mulsanne",
  "Bentley-Arnage",
  "Bentley-Brooklands",
  "Bentley-Azure",
  "Bentley-Continental Supersports",
  "Bentley-Turbo R",
  "Bentley-Turbo S",
  "Bentley-Series 51",
  "Bentley-T2",
  "Bentley-S3",
  "Bentley-Continental GT W12",
  "Bentley-Continental GT Speed Convertible",
  "Bentley-Flying Spur V8 Blackline",
  "Bentley-Bentayga V8 First Edition",
  "Bentley-Continental GT Supersports Convertible",
  "Bentley-Continental GT Mulliner Convertible",
  "Bentley-Bentley-Mulsanne Final Series",
  "Bentley-Flying Spur W12 Mulliner"
]
