"""
List of Bentley car models
Generated by create_model_list.py script
These are real car models across different price ranges
"""

model_list = [
    "Bentley-Continental GT",
    "Bentley-Flying Spur",
    "Bentley-Bentayga",
    "Bentley-Mulsanne",
    "Bentley-Continental GTC",
    "Bentley-Arnage",
    "Bentley-Brooklands",
    "Bentley-Azure",
    "Bentley-Continental Supersports",
    "Bentley-Turbo R",
    "Bentley-Turbo S",
    "Bentley-Continental GT Speed",
    "Bentley-Flying Spur Speed",
    "Bentley-Bentayga Speed",
    "Bentley-Continental GT Mulliner",
    "Bentley-Flying Spur Mulliner",
    "Bentley-Bentayga Hybrid",
    "Bentley-Series 51",
    "Bentley-T2",
    "Bentley-S3"
]
