"""
List of Bentley car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Bentley-Continental GT",
    "Bentley-Flying Spur",
    "Bentley-Bentayga",
    "Bentley-Mulsanne",
    "Bentley-Continental GTC",
    "Bentley-Arnage",
    "Bentley-Brooklands",
    "Bentley-Azure",
    "Bentley-Continental Supersports",
    "Bentley-Turbo R",
    "Bentley-Turbo S",
    "Bentley-Continental GT Speed",
    "Bentley-Flying Spur Speed",
    "Bentley-Bentayga Speed",
    "Bentley-Continental GT Mulliner",
    "Bentley-Flying Spur Mulliner",
    "Bentley-Bentayga Hybrid",
    "Bentley-Series 51",
    "Bentley-T2",
    "Bentley-S3",
    "Bentley-Continental GT V8 S",
    "Bentley-Flying Spur W12 Mulliner",
    "Bentley-Bentayga V8 First Edition",
    "Bentley-Continental GTC Speed Convertible",
    "Bentley-Flying Spur Hybrid",
    "Bentley-Bentayga Azure",
    "Bentley-Continental GT Supersports Convertible",
    "Bentley-Flying Spur V8 Blackline",
    "Bentley-Bentayga S",
    "Bentley-Continental GT Mulliner Convertible"
]
