"""
List of Mercedes-Benz car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Mercedes-Benz-A220 4MATIC Sedan",
    "Mercedes-Benz-C300 4MATIC Coupe",
    "Mercedes-Benz-E450 4MATIC All-Terrain Wagon",
    "Mercedes-Benz-S580 4MATIC Maybach",
    "Mercedes-Benz-GLC300 4MATIC Coupe",
    "Mercedes-Benz-GLE450 4MATIC AMG Line",
    "Mercedes-Benz-GLS600 4MATIC Maybach",
    "Mercedes-Benz-AMG GT 63 S 4MATIC+",
    "Mercedes-Benz-EQS580 4MATIC SUV",
    "Mercedes-Benz-SL55 AMG 4MATIC+ Roadster"
]
