"""
List of XPeng car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "XPeng-P7 RWD Long Range",
    "XPeng-P7 Performance AWD",
    "XPeng-G3 520i NEDC",
    "XPeng-G3i 460c",
    "XPeng-P5 550P",
    "XPeng-P5 600P",
    "XPeng-G9 650 Performance",
    "XPeng-G9 570 Max",
    "XPeng-P7 Wing Edition",
    "XPeng-P7i 610 Performance"
]
