"""
List of XPeng car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "XPeng-G6 625 Long-Range Max Technology Edition",
  "XPeng-G6 625 Long-Range Max Ultimate Edition",
  "XPeng-G6 725 Ultra-Long-Range Max Ultimate Edition",
  "XPeng-G9 625 Long-Range RWD",
  "XPeng-G9 725 Ultra-Long-Range RWD",
  "XPeng-G9 680 AWD Performance",
  "XPeng-P7+ Long Range",
  "XPeng-P7+ Ultra Long Range",
  "XPeng-P7+ Ultra Long Range Flagship",
  "XPeng-X9 650 Long-Range FWD",
  "XPeng-X9 702 Ultra-Long-Range AWD",
  "XPeng-X9 740 Ultra-Long-Range FWD",
  "XPeng-Mona M03 Standard Range",
  "XPeng-Mona M03 Long Range",
  "XPeng-Mona M03 Max"
]
