"""
List of Buick car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Buick-Encore",
  "Buick-Encore GX",
  "Buick-Envision",
  "Buick-Envision Avenir",
  "Buick-Empower",
  "Buick-Enclave",
  "Buick-Enclave Avenir",
  "Buick-Avista",
  "Buick-LaCrosse",
  "Buick-Regal",
  "Buick-Regal Sportback",
  "Buick-Regal GS",
  "Buick-Grand National",
  "Buick-Riviera",
  "Buick-Premium SUV"
]
