"""
List of all car brands extracted from CarLabels.toml
"""

brand_list = [
    "Volkswagen", 
    "Audi",
    "Porsche",
    "Bentley",
    "Bugatti", 
    "Lamborghini", 
    "BMW", 
    "Mercedes Benz",
    "Peugeot", 
    "Citroën", 
    "Renault", 
    "Jaguar", 
    "Land Rover", 
    "Rolls Royce", 
    "Volvo", 
    "Chevrolet", 
    "Buick",
    "Cadillac", 
    "Ford", 
    "Tesla", 
    "Toyota", 
    "Honda", 
    "Nissan", 
    "Suzuki",
    "Mazda",
    "Hyundai",
    "BYD", 
    "Geely", 
    "Changan",
    "GWM", 
    "Nio", 
    "XiaoMi",
    "XPeng",
]