"""
List of Jaguar car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Jaguar-Type 00",
  "Jaguar-Type 01",
  "Jaguar-Type 02",
  "Jaguar-Type 03",
  "Jaguar-I-PACE EV400",
  "Jaguar-I-PACE EV400 S",
  "Jaguar-I-PACE EV400 SE",
  "Jaguar-I-PACE EV400 HSE",
  "Jaguar-I-PACE EV400 First Edition",
  "Jaguar-XJ EV",
  "Jaguar-XJ EV Long Wheelbase",
  "Jaguar-XJ EV R-Dynamic",
  "Jaguar-XJ EV R-Sport",
  "Jaguar-XJ EV HSE",
  "Jaguar-F-Type EV",
  "Jaguar-F-Type EV R",
  "Jaguar-F-Type EV P300",
  "Jaguar-F-Type EV P400",
  "Jaguar-F-Type EV P450"
]
