"""
List of Jaguar car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Jaguar-F-Type R Coupe 5.0L V8",
    "Jaguar-XE SV Project 8 5.0L Supercharged",
    "Jaguar-XF S 3.0L V6 Diesel",
    "Jaguar-F-Pace SVR 5.0L V8",
    "Jaguar-I-Pace EV400 HSE",
    "Jaguar-XJ L Supercharged 5.0L V8",
    "Jaguar-E-Pace P250 R-Dynamic",
    "Jaguar-XK R-S GT 5.0L V8",
    "Jaguar-X-Type 3.0L V6 Sport",
    "Jaguar-S-Type R 4.2L V8"
]
