"""
List of Citroën car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Citro\u00ebn-C4 Picasso PureTech 130 S&S Feel",
    "Citro\u00ebn-C5 Aircross BlueHDi 180 Shine",
    "Citro\u00ebn-DS3 Performance THP 165",
    "Citro\u00ebn-Berlingo Multispace BlueHDi 120 Feel",
    "Citro\u00ebn-C3 Aircross PureTech 110 Shine",
    "Citro\u00ebn-Grand C4 Spacetourer BlueHDi 150 XTR",
    "Citro\u00ebn-C5 X Hybrid 225 Shine",
    "Citro\u00ebn-Ami 80% Electric",
    "Citro\u00ebn-Jumpy Combi BlueHDi 150 Enterprise",
    "Citro\u00ebn-DS5 Hybrid4 200 So Chic"
]
