"""
List of Chevrolet car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Chevrolet-Corvette Stingray Z51 3LT",
    "Chevrolet-Silverado 1500 High Country 6.2L V8",
    "Chevrolet-Tahoe RST Performance Edition",
    "Chevrolet-Camaro SS 1LE",
    "Chevrolet-Equinox Premier 1.5L Turbo",
    "Chevrolet-Malibu LT 1.5T",
    "Chevrolet-Trailblazer RS 1.3T AWD",
    "Chevrolet-Spark LS 1.4L",
    "Chevrolet-Suburban Premier 5.3L V8",
    "Chevrolet-Bolt EV Premier"
]
