"""
List of Chevrolet car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Chevrolet-Corvette Stingray",
  "Chevrolet-Corvette Z06",
  "Chevrolet-Corvette ZR1",
  "Chevrolet-Corvette E-Ray",
  "Chevrolet-Trax",
  "Chevrolet-Trailblazer",
  "Chevrolet-Equinox",
  "Chevrolet-Equinox EV",
  "Chevrolet-Blazer",
  "Chevrolet-Blazer EV",
  "Chevrolet-Traverse",
  "Chevrolet-Tahoe",
  "Chevrolet-Suburban",
  "Chevrolet-Colorado",
  "Chevrolet-Silverado 1500",
  "Chevrolet-Silverado HD",
  "Chevrolet-Silverado EV"
]
