"""
List of Lamborghini car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Lamborghini-Huracan EVO RWD Coupe",
    "Lamborghini-Aventador SVJ 63 Roadster",
    "Lamborghini-Urus Performante",
    "Lamborghini-Huracan STO",
    "Lamborghini-Revuelto V12 Hybrid",
    "Lamborghini-Aventador LP 780-4 Ultimae",
    "Lamborghini-Huracan Tecnica",
    "Lamborghini-Sian FKP 37",
    "Lamborghini-Countach LPI 800-4",
    "Lamborghini-Gallardo LP 560-4 Spyder"
]
