"""
List of Lamborghini car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Lamborghini-Revuelto",
  "Lamborghini-Revuelto Coupe",
  "Lamborghini-Revuelto Roadster",
  "Lamborghini-Temerario",
  "Lamborghini-Temerario Coupe",
  "Lamborghini-Urus",
  "Lamborghini-Urus SE",
  "Lamborghini-Urus Performante",
  "Lamborghini-Huracán Tecnica",
  "Lamborghini-Huracán STO",
  "Lamborghini-Huracán Sterrato",
  "Lamborghini-Huracán Evo Spyder",
  "Lamborghini-Huracán Evo Coupe",
  "Lamborghini-Huracán EVO RWD",
  "Lamborghini-Sian FKP 37",
  "Lamborghini-Sian Roadster",
  "Lamborghini-Aventador S",
  "Lamborghini-Aventador SVJ",
  "Lamborghini-Aventador SVJ Roadster",
  "Lamborghini-Aventador Ultimae",
  "Lamborghini-Aventador Ultimae Roadster"
]
