"""
List of Great Wall Motor car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
      "GWM-Haval M6",
  "GWM-Haval H5",
  "GWM-Haval H6",
  "GWM-Haval H6S",
  "GWM-Haval H7",
  "GWM-Haval H9",
  "GWM-Haval Jolion",
  "GWM-Haval Jolion Pro",
  "GWM-Haval Big Dog",
  "GWM-Haval Dargo X",
  "GWM-Haval Xiaolong",
  "GWM-Great Wall Poer",
  "GWM-Great Wall Poer EV",
  "GWM-Orchina",
  "GWM-Wingle 5",
  "GWM-Wingle 7",
  "GWM-Tank 300",
  "GWM-Tank 500",
  "GWM-Tank 700",
  "GWM-Tank 800"
]
