"""
List of Great Wall Motor car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Great Wall Motor-Haval H6 GT 2.0T",
    "Great Wall Motor-Paoche 300 2.0T 4WD",
    "Great Wall Motor-WEY VV7 GT 2.0T Luxury",
    "Great Wall Motor-Ora Good Cat 401km Pro",
    "Great Wall Motor-Tank 300 City Edition 2.0T",
    "Great Wall Motor-Haval Jolion 1.5T Premium",
    "Great Wall Motor-Poer Pickup 2.4T Diesel 4x4",
    "Great Wall Motor-WEY Mocha 2.0T PHEV",
    "Great Wall Motor-Ora Lightning Cat 600km AWD",
    "Great Wall Motor-Tank 500 3.0T V6 Luxury"
]
