"""
List of Rolls-Royce car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Rolls Royce-Spectre Luxury All-Electric Grand Tourer",
  "Rolls Royce-Spectre Black Badge High-Performance Electric Edition",
  "Rolls Royce-Ghost Series II Elegant Full-Size Luxury Sedan",
  "Rolls Royce-Ghost Series II Extended Extended Wheelbase Luxury Sedan",
  "Rolls Royce-Ghost Series II Black Badge Sportier High-Performance Sedan",
  "Rolls Royce-Phantom Series II Flagship Ultra-Luxury Sedan",
  "Rolls Royce-Phantom Series II Extended Extended Wheelbase Ultra-Luxury",
  "Rolls Royce-Phantom Series II Scintilla Private Bespoke Limited Edition",
  "Rolls Royce-Cullinan Series II Premium Full-Size Luxury SUV",
  "Rolls Royce-Cullinan Series II Black Badge Sportier Performance SUV"
]
