"""
List of Toyota car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Toyota-Camry XSE V6",
    "Toyota-Corolla LE Hybrid",
    "Toyota-RAV4 XLE Premium",
    "Toyota-Highlander Platinum AWD",
    "Toyota-Prius Prime Limited",
    "Toyota-Tacoma TRD Off-Road V6",
    "Toyota-Tundra 1794 Edition 5.7L",
    "Toyota-Sienna XSE FWD",
    "Toyota-Land Cruiser Heritage Edition",
    "Toyota-Supra 3.0 Premium"
]
