"""
List of Bugatti car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Bugatti-Chiron",
  "Bugatti-Chiron Sport",
  "Bugatti-Chiron Super Sport",
  "Bugatti-Chiron Pur Sport",
  "Bugatti-Chiron Profilée",
  "Bugatti-Divo",
  "Bugatti-Divo 110",
  "Bugatti-La Voiture Noire",
  "Bugatti-Veyron",
  "Bugatti-Veyron Super Sport",
  "Bugatti-Veyron Grand Sport Vitesse",
  "Bugatti-Veyron 16.4",
  "Bugatti-Bolide",
  "Bugatti-Bolide Prototype",
  "Bugatti-Centenary Edition",
  "Bugatti-Chiron Sport 300+",
  "Bugatti-Chiron Super Sport 300+"
]
