"""
List of Bugatti car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Bugatti-Chiron Super Sport 300+",
    "Bugatti-Veyron 16.4 Grand Sport Vitesse",
    "Bugatti-Divo",
    "Bugatti-Chiron Pur Sport",
    "Bugatti-Veyron 16.4",
    "Bugatti-Chiron Sport",
    "Bugatti-Centodieci",
    "Bugatti-La Voiture Noire",
    "Bugatti-Chiron Super Sport",
    "Bugatti-EB110 Super Sport"
]
