"""
List of BMW car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "BMW-M340i xDrive",
    "BMW-X5 xDrive40i",
    "BMW-330e M Sport",
    "BMW-M5 Competition",
    "BMW-X3 M40i",
    "BMW-740i xDrive",
    "BMW-Z4 sDrive30i",
    "BMW-X7 M50i",
    "BMW-228i Gran Coupe",
    "BMW-i4 M50"
]
