"""
List of Tesla car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Model S",
  "Model S Plaid",
  "Model 3 Standard RWD",
  "Model 3 Long Range RWD",
  "Model 3 Long Range AWD",
  "Model 3 Performance",
  "Model X",
  "Model X Plaid",
  "Model Y",
  "Model Y Long Range AWD",
  "Model Y Long Range RWD",
  "Model Y Performance",
  "Model Y Launch Series",
  "Model Q",
  "Model 2"
]
