"""
List of Tesla car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Tesla-Model 3 Long Range AWD",
    "Tesla-Model S Plaid",
    "Tesla-Model Y Performance",
    "Tesla-Model X Long Range",
    "Tesla-Model 3 Standard Range Plus RWD",
    "Tesla-Model S 100D",
    "Tesla-Model Y Long Range AWD",
    "Tesla-Model X Plaid",
    "Tesla-Model 3 Performance",
    "Tesla-Model S 75D"
]
