"""
List of Rolls-Royce car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Rolls-Royce Spectre",
  "Rolls-Royce Spectre Black Badge",
  "Rolls-Royce Ghost Series II",
  "Rolls-Royce Ghost Series II Extended",
  "Rolls-Royce Ghost Series II Black Badge",
  "Rolls-Royce Phantom Series II",
  "Rolls-Royce Phantom Series II Extended",
  "Rolls-Royce Phantom Series II Scintilla Private",
  "Rolls-Royce Cullinan Series II",
  "Rolls-Royce Cullinan Series II Black Badge"
]
