"""
List of Rolls-Royce car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Rolls-Royce-Phantom VIII EWB 6.75L V12",
    "Rolls-Royce-Ghost Black Badge 6.6L V12",
    "Rolls-Royce-Cullinan Black Badge 6.75L V12",
    "Rolls-Royce-Wraith Black Badge 6.6L V12",
    "Rolls-Royce-Dawn Black Badge 6.6L V12",
    "Rolls-Royce-Spectre Dual-Motor EV",
    "Rolls-Royce-Phantom VIII Extended 6.75L V12",
    "Rolls-Royce-Ghost Extended 6.75L V12",
    "Rolls-Royce-Cullinan Series II 6.75L V12",
    "Rolls-Royce-Wraith Aero Coupe 6.6L V12"
]
