"""
List of Renault car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Renault-5 E-Tech Evolution Electric Compact Hatchback",
  "Renault-5 E-Tech Techno Advanced Trim Electric Hatchback",
  "Renault-5 E-Tech Iconic Premium Electric Hatchback",
  "Renault-5 E-Tech Alpine A290 GT Sporty Electric Edition",
  "Renault-5 E-Tech Alpine A290 GTS High-Performance Electric",
  "Renault-4 E-Tech Electric Classic-Inspired Compact",
  "Renault-4 E-Tech Alpine Sport-Tuned Electric Model",
  "Renault-5 Turbo 3E Retro-Inspired Turbocharged EV",
  "Renault-Mégane E-Tech Electric Compact Electric Hatchback",
  "Renault-Scénic E-Tech Electric Family-Oriented Electric MPV",
  "Renault-Austral Evolution Stylish Compact SUV",
  "Renault-Austral Techno Mid-Trim Premium Compact SUV",
  "Renault-Austral Esprit Alpine Sporty High-Performance SUV",
  "Renault-Espace Techno 5-Sitzer Mid-Trim 5-Seater SUV",
  "Renault-Espace Techno 7-Sitzer Mid-Trim 7-Seater SUV",
  "Renault-Espace Esprit Alpine 5-Sitzer Sporty 5-Seater SUV",
  "Renault-Espace Esprit Alpine 7-Sitzer Sporty 7-Seater SUV",
  "Renault-Espace Iconic 5-Sitzer Luxury 5-Seater SUV",
  "Renault-Espace Iconic 7-Sitzer Luxury 7-Seater SUV",
  "Renault-Rafale Esprit Alpine Performance-Oriented Crossover",
  "Renault-Rafale Iconic Premium Trim Crossover",
  "Renault-Captur Subcompact Urban Crossover SUV",
  "Renault-Clio Popular Subcompact Hatchback",
  "Renault-Kangoo Compact Utility Van",
  "Renault-Twingo E-Tech Electric City Electric Hatchback",
  "Renault-Kangoo E-Tech Electric Electric Utility Van",
  "Renault-Master Large Commercial Van",
  "Renault-Trafic Mid-Size Commercial Van",
  "Renault-Express Compact Utility Van",
  "Renault-Triber Affordable Compact MPV",
  "Renault-Kwid Entry-Level Compact City Car",
  "Renault-Kiger Compact Urban SUV",
  "Renault-Duster Rugged Budget-Friendly SUV",
  "Renault-Bigster Upcoming Large SUV Concept"
]
