"""
List of Renault car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Renault-Clio RS Line 1.3 TCe",
    "Renault-M\u00e9gane R.S. Trophy 1.8",
    "Renault-Captur Iconic 1.0 TCe",
    "Renault-Kadjar GT Line dCi 150",
    "Renault-Talisman Initiale Paris dCi 160",
    "Renault-Zoe R135 GT Line",
    "Renault-Koleos Intens dCi 190",
    "Renault-Twingo GT 1.0 SCe",
    "Renault-Scenic Business dCi 115",
    "Renault-Alpine A110 Pure"
]
