"""
List of Renault car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Renault 5 E-Tech Evolution",
  "Renault 5 E-Tech Techno",
  "Renault 5 E-Tech Iconic",
  "Renault 5 E-Tech Alpine A290 GT",
  "Renault 5 E-Tech Alpine A290 GTS",
  "Renault 4 E-Tech",
  "Renault 4 E-Tech Alpine",
  "Renault 5 Turbo 3E",
  "Renault Mégane E-Tech Electric",
  "Renault Scénic E-Tech Electric",
  "Renault Austral Evolution",
  "Renault Austral Techno",
  "Renault Austral Esprit Alpine",
  "Renault Espace Techno 5-Sitzer",
  "Renault Espace Techno 7-Sitzer",
  "Renault Espace Esprit Alpine 5-Sitzer",
  "Renault Espace Esprit Alpine 7-Sitzer",
  "Renault Espace Iconic 5-Sitzer",
  "Renault Espace Iconic 7-Sitzer",
  "Renault Rafale Esprit Alpine",
  "Renault Rafale Iconic",
  "Renault Captur",
  "Renault Clio",
  "Renault Kangoo",
  "Renault Twingo E-Tech Electric",
  "Renault Kangoo E-Tech Electric",
  "Renault Master",
  "Renault Trafic",
  "Renault Express",
  "Renault Triber",
  "Renault Kwid",
  "Renault Kiger",
  "Renault Duster",
  "Renault Bigster"
]
