"""
List of Land Rover car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
    "Land Rover-Defender 110 P400 SE",
    "Land Rover-Range Rover Sport SVR 5.0L V8",
    "Land Rover-Discovery Sport P250 R-Dynamic SE",
    "Land Rover-Range Rover Velar P340 R-Dynamic HSE",
    "Land Rover-Defender 90 D250 SE",
    "Land Rover-Range Rover P400 Autobiography LWB",
    "Land Rover-Discovery TD6 HSE Luxury",
    "Land Rover-Range Rover Evoque P200 R-Dynamic S",
    "Land Rover-Defender 130 X P400",
    "Land Rover-Range Rover Sport P400e HSE Dynamic"
]
