"""
List of Land Rover car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Land Rover-Defender 90 S Compact Off-Road SUV",
  "Land Rover-Defender 90 X-Dynamic SE Premium Edition",
  "Land Rover-Defender 90 X-Dynamic HSE High-Spec Trim",
  "Land Rover-Defender 90 X Performance-Oriented Model",
  "Land Rover-Defender 90 V8 High-Performance Edition",
  "Land Rover-Defender90 V8 Carpathian Edition Luxury Off-Roader",
  "Land Rover-Defender 110 S Midsize Adventure SUV",
  "Land Rover-Defender 110 X-Dynamic SE Premium Explorer",
  "Land Rover-Defender 110 X-Dynamic HSE Luxury Explorer Edition",
  "Land Rover-Defender 110 X High-End Utility Vehicle",
  "Land Rover-Defender 110 V8 Advanced Capability Edition",
  "Land Rover-Defender 110 V8 Carpathian Edition Flagship Model",
  "Land Rover-Defender 130 Outbound Extended-Length Overlander",
  "Land Rover-Range Rover SE Entry-Level Luxury SUV",
  "Land Rover-Range Rover Autobiography Executive Luxury Trim",
  "Land Rover-Range Rover SV Ultra-Luxury Flagship Edition",
  "Land Rover-Range Rover P400 Mild Hybrid I6 Petrol",
  "Land Rover-Range Rover P530 V8 Twin-Turbo Powertrain",
  "Land Rover-Range Rover P550e PHEV Plug-In Hybrid",
  "Land Rover-Range Rover P460e PHEV Efficient Plug-In Variant",
  "Land Rover-Range Rover Long Wheelbase (LWB) Extended Rear Legroom",
  "Land Rover-Range Rover Long Wheelbase (LWB) SV Top-Tier Luxury Edition",
  "Land Rover-Range Rover Long Wheelbase (LWB) Autobiography Executive Seating Edition",
  "Land Rover-Range Rover Sport SE Performance Entry Trim",
  "Land Rover-Range Rover Sport Autobiography Executive SUV",
  "Land Rover-Range Rover Sport SV Edition Two High-Performance Model",
  "Land Rover-Range Rover Sport P400 Mild Hybrid Sport SUV",
  "Land Rover-Range Rover Sport P530 V8 Twin-Turbo Power",
  "Land Rover-Range Rover Sport P550e PHEV High-Efficiency Plug-In Hybrid",
  "Land Rover-Range Rover Sport P460e PHEV Mid-Range Plug-In Hybrid",
  "Land Rover-Range Rover Velar S Stylish Midsize SUV",
  "Land Rover-Range Rover Velar R-Dynamic SE Sportier Design Trim",
  "Land Rover-Range Rover Velar R-Dynamic HSE High-Spec Sport Package",
  "Land Rover-Range Rover Evoque S Compact Urban SUV",
  "Land Rover-Range Rover Evoque R-Dynamic SE Enhanced City Trim",
  "Land Rover-Range Rover Evoque R-Dynamic HSE Luxury Urban Edition",
  "Land Rover-Range Rover Evoque Autobiography Top-Tier Compact SUV"
]
