"""
List of Land Rover car models
Generated by create_model_list.py script
These are real car models across different price ranges
IMPORTANT: These are specific model variants (not just series names) to ensure accurate specifications
"""

model_list = [
  "Defender 90 S",
  "Defender 90 X-Dynamic SE",
  "Defender 90 X-Dynamic HSE",
  "Defender 90 X",
  "Defender 90 V8",
  "Defender 90 V8 Carpathian Edition",
  "Defender 110 S",
  "Defender 110 SE",
  "Defender 110 X-Dynamic SE",
  "Defender 110 X-Dynamic HSE",
  "Defender 110 X",
  "Defender 110 V8",
  "Defender 110 V8 Carpathian Edition",
  "Defender 130 Outbound",
  "Range Rover SE",
  "Range Rover Autobiography",
  "Range Rover SV",
  "Range Rover P400",
  "Range Rover P530",
  "Range Rover P550e PHEV",
  "Range Rover P460e PHEV",
  "Range Rover Long Wheelbase (LWB)",
  "Range Rover Long Wheelbase (LWB) SV",
  "Range Rover Long Wheelbase (LWB) Autobiography",
  "Range Rover Sport SE",
  "Range Rover Sport Autobiography",
  "Range Rover Sport SV Edition Two",
  "Range Rover Sport P400",
  "Range Rover Sport P530",
  "Range Rover Sport P550e PHEV",
  "Range Rover Sport P460e PHEV",
  "Range Rover Velar S",
  "Range Rover Velar R-Dynamic SE",
  "Range Rover Velar R-Dynamic HSE",
  "Range Rover Velar SVAutobiography Dynamic",
  "Range Rover Evoque S",
  "Range Rover Evoque R-Dynamic SE",
  "Range Rover Evoque R-Dynamic HSE",
  "Range Rover Evoque Autobiography"
]
